### ISSUE TITLE
I renamed config & got this

### ISSUE THREAD

**Issue by AnyGiv3nDay** [Pr0nBotDev/Pr0nBot#1]
RIP no config
Traceback (most recent call last):
  File "C:\Users\fam\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 580, in _load_from_module_spec
    setup(self)
  File "C:\Users\fam\Desktop\bot\PornHub.py", line 657, in setup
    bot.add_cog(PornHub(bot))
  File "C:\Users\fam\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 480, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\fam\Desktop\bot\MainBot.py", line 44, in <module>
    bot.load_extension("PornHub")
  File "C:\Users\fam\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 625, in load_extension
    self._load_from_module_spec(lib, name)
  File "C:\Users\fam\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 584, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'PornHub' raised an error: TypeError: cogs must derive from Cog

**Comment by baranykristof** [comment]
There was a command in the PornHub.py class. Cog must be a descendant, that's all I've found so far
cow class PornHub: replace class PornHub(commands.Cog):

**Comment by baranykristof** [comment]
Edit the PornHub.py and  change class PornHub: to class PornHub(commands.Cog):

**Comment by RounakX** [comment]
Did you get any result for that? @AnyGiv3nDay
