### ISSUE TITLE
This Error keeps on happening while running MainBot.py

### ISSUE THREAD

**Issue by RounakX** [Pr0nBotDev/Pr0nBot#2]
==================== RESTART: D:\F2\Pr0nBot\MainBot.py ======================
Traceback (most recent call last):
  File "D:\Users\RDX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 608, in _load_from_module_spec
    setup(self)
  File "D:\F2\Pr0nBot\PornHub.py", line 657, in setup
    bot.load_extension(PornHub(bot))
  File "D:\Users\RDX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 649, in load_extension
    spec = importlib.util.find_spec(name)
  File "D:\Users\RDX\AppData\Local\Programs\Python\Python38-32\lib\importlib\util.py", line 90, in find_spec
    fullname = resolve_name(name, package) if name.startswith('.') else name
AttributeError: 'PornHub' object has no attribute 'startswith'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\F2\Pr0nBot\MainBot.py", line 42, in <module>
    bot.load_extension("PornHub")
  File "D:\Users\RDX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "D:\Users\RDX\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 613, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'PornHub' raised an error: AttributeError: 'PornHub' object has no attribute 'startswith'

**Comment by chicoze2** [comment]
did u fixed it?

**Comment by chicoze2** [comment]
try using 'user_cog' instead of 'load_extension'

**Comment by samalzpro49** [comment]
This bot is written in discord.js 1.0 so you have to update the script to discord.js to 2.0
